CREATE TABLE SPRING_IMG_TBL(
	IMGPATH 		VARCHAR2(100) PRIMARY KEY,
	TITLE 		VARCHAR2(100), 
	CONTENT 		VARCHAR2(2000),
	BADGEVALUE 	NUMBER
	);
	
INSERT INTO SPRING_IMG_TBL
VALUE ('DSC_6305.jpg', '첫번째', '냉무', 10);

INSERT INTO SPRING_IMG_TBL
VALUES ('DSC_0374.jpg','두번째','냉무',20);

INSERT INTO SPRING_IMG_TBL
VALUES ('DSC_5041.jpg','세번째','냉무',30);

INSERT INTO SPRING_IMG_TBL
VALUES ('DSC_4999.jpg','네번째','냉무',40);



CREATE TABLE SPRING_USER_TBL(
	ID 		VARCHAR2(50) PRIMARY KEY,
	PWD 		VARCHAR2(50) NOT NULL,
	NAME 	VARCHAR2(50) NOT NULL,
	UPOINT 	NUMBER DEFAULT 0  NOT NULL,	
	SESSIONKEY VARCHAR2(50)  DEFAULT 'NONE' NOT NULL,
	SESSIONLIMIT DATE,
    IMGSRC  VARCHAR2(50)
);

CREATE TABLE SPRING_BOARD_TBL(
    SEQ              NUMBER PRIMARY KEY,
    TITLE            VARCHAR2(50) NOT NULL,
    CONTENT    VARCHAR2(2000) NOT NULL,
    WRITER        VARCHAR2(20) REFERENCES SPRING_USER_TBL(ID),
    REGDATE      DATE,
    VIEWCNT      NUMBER
);


CREATE SEQUENCE SPRINGBOARDSEQ;

INSERT INTO SPRING_BOARD_TBL
VALUES(SPRINGBOARDSEQ.NEXTVAL, '공지', '메롱', 'admin', SYSDATE, 0);

SELECT * FROM SPRING_BOARD_TBL;


SELECT * FROM
(
    SELECT ROWNUM AS RNUM, GET.* FROM
    (
        SELECT * FROM SPRING_BOARD_TBL
    )GET
    ORDER BY ROWNUM DESC
)
WHERE RNUM BETWEEN 1 AND 10 ORDER BY RNUM ASC;




