CREATE TABLE SSGIN_USER_TBL (
	USER_NO		NUMBER			PRIMARY KEY,
	HASH		VARCHAR2(50)	NOT NULL	
);

SELECT * FROM SSGIN_USER_TBL;

CREATE	TABLE	SSGIN_LOG_TBL (
	USER_NO			NUMBER	REFERENCES	SSGIN_USER_TBL(USER_NO),
	AUTH_TIME		VARCHAR2(20)			NOT NULL,
	AUTH_SUCCESS	CHAR(1)	DEFAULT	'Y'		NOT NULL,
	AUTH_URL		VARCHAR2(20)			NOT NULL
);

DROP TABLE SSGIN_LOG_TBL

CREATE	TABLE	SSGIN_ADMIN_TBL (
	ADMIN_ID	VARCHAR2(20)	PRIMARY KEY,
	ADMIN_PWD	VARCHAR2(20)	NOT NULL
);

SELECT * FROM SSGIN_NOTICE_TBL;

CREATE	TABLE	SSGIN_FAQ_TBL (
	FAQ_SEQ			NUMBER			PRIMARY	KEY,
	FAQ_CATEGORY	VARCHAR2(20)	DEFAULT 'ALL' NOT NULL,
	FAQ_TITLE		VARCHAR2(50)	NOT NULL,
	FAQ_CONTENT		VARCHAR2(2000)	NOT NULL
)

CREATE SEQUENCE	SSGINFAQSEQ;

CREATE	TABLE	SSGIN_NOTICE_TBL (
	NOTICE_SEQ		NUMBER			PRIMARY KEY,
	NOTICE_TITLE	VARCHAR2(50)	NOT NULL,
	NOTICE_CONTENT	VARCHAR2(2000)	NOT NULL,
	NOTICE_REGDATE	VARCHAR2(20)	NOT NULL
)

DROP TABLE SSGIN_NOTICE_TBL

INSERT INTO SSGIN_NOTICE_TBL(NOTICE_SEQ, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_REGDATE)
VALUES (SSGINNOTICESEQ.NEXTVAL, 'SSG IN 정식 서비스 시작!', '블록체인을 통해 안전한 인증을 시도해보세요!', TO_CHAR(SYSDATE,'YYYY-MM-DD'));
INSERT INTO SSGIN_NOTICE_TBL(NOTICE_SEQ, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_REGDATE)
VALUES (SSGINNOTICESEQ.NEXTVAL, 'SSG IN 222', '블록체인을 통해 안전한 인증을 시도해보세요!', TO_CHAR(SYSDATE,'YYYY-MM-DD'));

CREATE SEQUENCE	SSGINNOTICESEQ;

CREATE	TABLE	SSGIN_EVENT_TBL (
	EVENT_NO			NUMBER			PRIMARY KEY,
	EVENT_IMGSRC		VARCHAR2(180),
	EVENT_LINK			VARCHAR2(50),
	EVENT_TITLE			VARCHAR2(50)	NOT NULL,
	EVENT_START_DATE	VARCHAR2(20)	NOT NULL,
	EVENT_END_DATE		VARCHAR2(20)
)

DROP TABLE SSGIN_EVENT_TBL

CREATE SEQUENCE	SSGINEVENTSEQ;



select * from ssgin_notice_tbl where notice_seq = 25


SELECT NOTICE_SEQ, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_DATE FROM
(
	SELECT ROWNUM AS RNUM, GET.* FROM
	(
	SELECT * FROM SSGIN_NOTICE_TBL
	) GET
	ORDER BY RNUM ASC 
)
WHERE RNUM BETWEEN 1 AND 10;




INSERT INTO SSGIN_FAQ_TBL(FAQ_SEQ, FAQ_CATEGORY, FAQ_TITLE, FAQ_CONTENT)
VALUES (SSGINFAQSEQ.NEXTVAL, '일반', 'SSG IN은 어떤 서비스인가요?', '블록체인 기반 간편본인인증시스템 입니다.');

INSERT INTO SSGIN_FAQ_TBL(FAQ_SEQ, FAQ_CATEGORY, FAQ_TITLE, FAQ_CONTENT)
VALUES (SSGINFAQSEQ.NEXTVAL, '인증', '인증이란 무엇인가요?', '정당한 사용자의 신원을 확인하는 것입니다.');

SELECT * FROM SSGIN_FAQ_TBL

DROP TABLE SSGIN_FAQ_TBL


